name: Code Quality Checks

on:
  pull_request:
    branches: [main]

jobs:
  build:
    name: Build Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt  # Adjust this based on your project

  test:
    name: Test Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run Tests
        run: pytest  # Change if using a different test framework

  lint:
    name: Lint Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: pip install flake8
      - name: Run Linter
        run: flake8 .
